name: .NET Core Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./NorthWindService/NorthWindService.csproj
      
    - name: Build
      run: dotnet build ./NorthWindService/NorthWindService.csproj --no-restore
      
    - name: Test
      run: dotnet test ./NorthWindUnitTest/NorthWindUnitTest/NorthWindUnitTest.csproj --logger "trx;LogFileName=test-results.trx" --results-directory TestResults
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3  # 更新到 v3
      with:
        name: Test Results
        path: TestResults
