name: .NET Core Build and Test Report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  checks: write

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./NorthWindService/NorthWindService.csproj
      
    - name: Build
      run: dotnet build ./NorthWindService/NorthWindService.csproj --no-restore --configuration Release
      
    - name: Test with Coverage
      run: dotnet test ./NorthWindUnitTest/NorthWindUnitTest/NorthWindUnitTest.csproj 
           --no-build 
           --configuration Release
           --logger "trx;LogFileName=test-results.trx" 
           --collect:"XPlat Code Coverage"
           --results-directory TestResults
           
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
      
    - name: Generate Comprehensive Report
      run: reportgenerator 
           -reports:TestResults/**/coverage.cobertura.xml 
           -targetdir:TestResults/CoverageReport 
           -reporttypes:"Html;HtmlSummary;Cobertura;TextSummary;Badges;TeamCitySummary;PngChart"
           
    - name: Generate Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Quality Assurance Test Report
        path: TestResults/test-results.trx
        reporter: dotnet-trx
        fail-on-error: true

    - name: Package Reports
      if: always()
      run: |
        echo "Test Report Generation Date: $(Get-Date -Format "yyyy-MM-dd HH:mm")" > TestResults/report-info.txt
        echo "Project: NorthWindService" >> TestResults/report-info.txt
        echo "Version: $(git describe --tags --always)" >> TestResults/report-info.txt
        Compress-Archive -Path TestResults/* -DestinationPath TestResults/QA_Report.zip
        
    - name: Upload Full Report Package
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: QA_Report_Package
        path: TestResults/QA_Report.zip
        retention-days: 90
